# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# Find the sum of all the even-valued terms in the sequence which do not exceed four million.
result = 0
a = [1,2]
(2..33).each do |i|
#  if (a[i] < 400000)
    a << a[i-2] + a[i-1] 
  result = result + a[i-2] if a[i-2] % 2 == 0 && a[i-2] < 4000000
#  end
end

puts result
